### ISSUE TITLE
CI (deploy step) fails on master

### ISSUE THREAD

**Issue by loicteixeira** [springload/awesome-wagtail#119]
The last deploy step fails on master with the message `Couldn't push the build to github.com/springload/awesome-wagtail.git:gh-pages` which should correspond to this step:

https://github.com/springload/awesome-wagtail/blob/95849a4129a19df52f81898073403178ad04e6fc/.travis.yml#L12-L18

I'm betting on a expired/deleted token which would either be set in the Travis settings or encrypted in the `.travis.yml`. Either way, I can't change it myself.

**Comment by mojeto** [comment]
Hi @loicteixeira, thank you for finding it out. I'll see what's broken.
