### ISSUE TITLE
wagtail_textract not compatible with current Wagtail

### ISSUE THREAD

**Issue by valduris** [springload/awesome-wagtail#155]
https://github.com/fourdigits/wagtail_textract/issues/31

It would be nice to update the list by removing wagtail_textract from it or adding some kind of warning symbol.

**Comment by loicteixeira** [comment]
Thanks for the report @valf, and sorry for the late reply.

@allcaps, Does Four Digits have plans to fix compatibility issues for Wagtail Textract any time soon? Otherwise, I'll remove it from the list until it sees an update.

**Comment by valduris** [comment]
Is this "awesome" list still maintained?
