### ISSUE TITLE
Offer to help review/approve PRs

### ISSUE THREAD

**Issue by lb-** [springload/awesome-wagtail#178]
Hi,

There are a few PRs dating back a few months (multiple are mine), I would like to see if I can help reviewing/approving PRs or if there is an opportunity for some other Wagtail core team members to be given access to this repo.

Thanks

**Comment by KalobTaulien** [comment]
I'd be happy to help maintain this repo (and am a Wagtail core member)

**Comment by mojeto** [comment]
Hi, I have invited @lb- @thibaudcolas and @loicteixeira so far to become awesome-wagtail repository maintainers as agreed between  Springload and Torchbox.

**Comment by lb-** [comment]
@mojeto thanks for this, I'll be careful to ensure PRs follow the existing guidelines. 

I'll start to look at some of the existing PRs over the next week or so.

**Comment by lb-** [comment]
I think we can close this as resolved now. Thank you.
