### ISSUE TITLE
README requires review

### ISSUE THREAD

**Issue by ppo** [springload/awesome-wagtail#203]
On the 4 links I tried, 2 have problems… so I guess there are more problems.

In **Templates & Starter Kits**:
* [Wagtail Starter Kit](https://github.com/tkjone/starterkit-wagtail) = broken link
* [Wagtail bootstrap blog](https://github.com/AccordBox/wagtail-bootstrap-blog) redirects to wagtail-tailwind-blog

**Comment by thibaudcolas** [comment]
Thanks @ppo! PR welcome.

**Comment by lb-** [comment]
PR up for this section (tutorial/starter links) https://github.com/springload/awesome-wagtail/pull/206
