### ISSUE TITLE
Need split 1 and 2 branch of wagtail

### ISSUE THREAD

**Issue by mmmcorpsvit** [springload/awesome-wagtail#73]
1 and 2 branch not compatible, very need complete info about support 2 version of wagtail

**Comment by thibaudcolas** [comment]
Hey @mmmcorpsvit, perhaps we could add a link to https://wagtail.io/blog/upgrading-to-wagtail-2/ in the "Articles" section? At the same time it could also be worth linking to the official Wagtail blog in the "General resources" section, even if the Wagtail website is already there.
