### ISSUE TITLE
404 at URL in repo description

### ISSUE THREAD

**Issue by gardner** [springload/awesome-wagtail#96]
Hello! Thank you for curating this list of awesome resources for Wagtail! I would like to let you know that the URL in the repo description returns a 404 for me. (https://www.springload.co.nz/blog/awesome-wagtail/)

Cheers,
  Gardner

**Comment by loicteixeira** [comment]
Indeed. Thanks for the report @gardner.

@dnsl48, @mojeto: Can one of you remove the link to the Springload's blog in the repo description and close this issue? I apparently don't have the permissions to do so. Thanks!

**Comment by dnsl48** [comment]
@tacitus ^^^

**Comment by mojeto** [comment]
I've removed the url @loicteixeira from the repository. I'm investigating why the blog post disappeared. By looking into an [old version of the blog post](http://web.archive.org/web/20180130075747/https://www.springload.co.nz/blog/awesome-wagtail/) I don't see any important info for this project.

**Comment by mojeto** [comment]
I may add the url back If I found where the blog post is.
Thanks for raising it @gardner
